name: build-client

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-compile:
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Compile step
        run: "deno compile --no-check --allow-read --allow-write --allow-net --allow-env --allow-run --output lucid-adventure-${{ matrix.platform }} ./src/mod.ts"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lucid-adventure-${{ matrix.platform }}
            lucid-adventure-${{ matrix.platform }}.exe
